#!/usr/bin/env bash
# AI Kit — self-test.   bash tests/run.sh
#   AI_TEST_LATEST=0   use the e2e deps already installed (default 1: npm i <every dep>@latest first —
#                      the reference code is proven against what `npm i` gives a project TODAY)
#   AI_TEST_KEEP=1     keep the scratch dir
set -uo pipefail
export USER="${USER:-$(id -un)}"
KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T="$(mktemp -d "${TMPDIR:-/tmp}/ai-test.XXXXXX")"; [ -n "${AI_TEST_KEEP:-}" ] && echo "kept: $T" || trap 'rm -rf "$T"' EXIT
pass=0; fail=0
ok()  { echo "  ✓ $1"; pass=$((pass+1)); }
bad() { echo "  ✗ $1"; fail=$((fail+1)); }
expect() {  # expect <desc> <exit-code> <grep-pattern|-> <cmd...>
    local d="$1" want="$2" pat="$3"; shift 3
    out="$("$@" 2>&1)"; code=$?
    if [ "$code" != "$want" ]; then bad "$d (exit $code, want $want)"; echo "$out" | sed 's/^/      /' | head -12; return; fi
    if [ "$pat" != - ] && ! grep -qE -- "$pat" <<<"$out"; then bad "$d (missing /$pat/)"; echo "$out" | sed 's/^/      /' | head -12; return; fi
    ok "$d"
}
export AI_NO_PLUGINS=1   # plugin enabling is exercised by the live install, not the unit run
# shellcheck source=install/lib.sh
KIT_BINS="$(sed -n 's/^KIT_BINS="\(.*\)"/\1/p' "$KIT/install/lib.sh")"

echo "▶ scripts parse + every CLI answers --help"
n=0; for f in "$KIT"/install/*.sh "$KIT"/bin/*; do
    head -1 "$f" | grep -q python && { python3 -m py_compile "$f" 2>/dev/null || bad "py_compile $f"; } || { bash -n "$f" 2>/dev/null || bad "bash -n $f"; }; n=$((n+1)); done
ok "$n scripts parse (bash -n / py_compile)"
# bash 3.2 in a UTF-8 locale treats high bytes as name chars: a $var glued to a non-ASCII char is an unbound variable under set -u
utf_lint() {  # a function, not $(…): bash 3.2 misparses case patterns inside command substitution
    local f
    git ls-files | while read -r f; do
        case "$f" in *.sh) ;; *) head -1 "$f" 2>/dev/null | grep -q bash || continue ;; esac
        perl -ne 'print "$ARGV:$. " if /(?<!\\)\$[A-Za-z_][A-Za-z0-9_]*[^\x00-\x7F]/' "$f"
    done
}
utf="$(cd "$(dirname "$0")/.." && utf_lint)"
[ -z "$utf" ] && ok "no \$var glued to a non-ASCII char (bash 3.2 + UTF-8 locale crash)" || bad "\$var followed by non-ASCII — write \${var}: $utf"
for b in $KIT_BINS; do "$KIT/bin/$b" --help >/dev/null 2>&1 || bad "$b --help"; done; ok "$(echo $KIT_BINS | wc -w | tr -d ' ') CLIs answer --help"

echo "▶ one AI brain (map ↔ installed skills ↔ sibling kits)"
python3 "$KIT/tests/brain_check.py" "$KIT" >"$T/brain.log" 2>&1; n_ok=$(grep -c '^OK' "$T/brain.log")
grep -q '^FAIL' "$T/brain.log" && { bad "brain consistency"; grep '^FAIL' "$T/brain.log"; } \
  || ok "brain: $n_ok checks — map names only installed skills, no duplicates across kits, every skill placed, identity + freedom rules stated"
grep '^SKIP' "$T/brain.log" | sed 's/^/  · /'

echo "▶ reference code vs the LATEST AI SDK (typecheck + e2e with mock models, no network calls to models)"
E="$KIT/tests/e2e"
if command -v npm >/dev/null; then
    if [ "${AI_TEST_LATEST:-1}" = 1 ]; then
        deps="$(node -p 'const p=require(process.argv[1]); Object.keys({...p.dependencies,...p.devDependencies}).map(d=>d+"@latest").join(" ")' "$E/package.json")"
        # shellcheck disable=SC2086
        (cd "$E" && npm i --no-save --no-audit --no-fund $deps >"$T/npm.log" 2>&1) || { bad "npm i @latest"; tail -5 "$T/npm.log"; }
    else (cd "$E" && { [ -d node_modules ] || npm i --no-audit --no-fund >"$T/npm.log" 2>&1; }); fi
    ln -sfn tests/e2e/node_modules "$KIT/node_modules"
    v="$(node -p 'require(process.argv[1]).version' "$E/node_modules/ai/package.json" 2>/dev/null)"
    (cd "$E" && npx tsc -p . >"$T/tsc.log" 2>&1) && ok "all references typecheck (strict) against ai@$v" || { bad "typecheck"; head -20 "$T/tsc.log"; }
    (cd "$E" && npx tsx --test --test-reporter=tap ./*.test.ts >"$T/e2e.log" 2>&1)
    np="$(sed -n 's/^# pass //p' "$T/e2e.log")"; nf="$(sed -n 's/^# fail //p' "$T/e2e.log")"
    [ "${nf:-1}" = 0 ] && [ "${np:-0}" -ge 40 ] && ok "e2e: $np behaviour tests (identity lock, scope lock, signed approvals, real HTTP stream, SMS YES, failover, eval gate, typed decisions on the wire, ML, bus, webhooks)" \
      || { bad "e2e ($np pass, $nf fail)"; grep -E "^not ok|error:|Error" "$T/e2e.log" | head -20; }
else echo "  · npm not found — e2e skipped"; fi

if command -v createdb >/dev/null && command -v psql >/dev/null && psql -Atc "select 1" postgres >/dev/null 2>&1 && [ -d "$E/node_modules/drizzle-kit" ]; then
    echo "▶ analytics SQL on real Postgres (schema generated by drizzle-kit from ai-schema.ts)"
    D="$T/sql"; DB="ai_selftest_$$"; mkdir -p "$D"; cp "$KIT/skills/ai-kit/references/ai-schema.ts" "$D/schema.ts"; ln -s "$E/node_modules" "$D/node_modules"
    printf 'import { defineConfig } from "drizzle-kit";\nexport default defineConfig({ dialect: "postgresql", schema: "./schema.ts", out: "./out" });\n' > "$D/drizzle.config.ts"
    vec="$(psql -XAtc "select 1 from pg_available_extensions where name='vector'" postgres 2>/dev/null)"
    if (cd "$D" && npx drizzle-kit generate >"$T/dk.log" 2>&1) && createdb "$DB" \
       && { [ "$vec" = 1 ] && psql -XqAtc "create extension vector" "$DB" >/dev/null && sed 's/--> statement-breakpoint//' "$D"/out/*.sql \
            || sed 's/--> statement-breakpoint//; s/vector([0-9]*)/real[]/g' "$D"/out/*.sql; } | psql -X -q -v ON_ERROR_STOP=1 "$DB" >/dev/null 2>"$T/ddl.log"; then
        ok "drizzle-kit DDL applies cleanly ($(grep -c 'CREATE TABLE' "$D"/out/*.sql) tables$([ "$vec" = 1 ] && echo ', pgvector' || echo '; no pgvector here → vector mapped to real[]'))"
        psql -X -q -v ON_ERROR_STOP=1 -f "$KIT/tests/fixtures/seed.sql" "$DB" >/dev/null 2>"$T/seed.log" && ok "seeded a hand-computed week" || { bad "seed"; head -5 "$T/seed.log"; }
        R() { AI_DATABASE_URL="postgres:///$DB" "$KIT/bin/ai-report" --csv --days 7 "$@" 2>&1; }
        all="$(AI_DATABASE_URL="postgres:///$DB" "$KIT/bin/ai-report" --days 7 2>&1)"; [ $? = 0 ] && ok "all $(grep -c '^▶' <<<"$all") named queries run (ai-report exit 0)" || { bad "ai-report"; grep '✗' <<<"$all"; }
        grep -qx "web,3,66.7,33.3,3.0,5.00,66.7" <<<"$(R conversations_by_channel)" && ok "conversations_by_channel: 3 web convs, 66.7% AI-resolved, thumbs 66.7% (feedback not double-counted)" || bad "conversations_by_channel: $(R conversations_by_channel | tail -2 | tr '\n' ' ')"
        grep -qx "0.0267" <<<"$(R cost_per_resolution)" && ok "cost per resolution \$0.0267 (80k µ\$ / 3 resolutions)" || bad "cost_per_resolution: $(R cost_per_resolution | tail -1)"
        grep -qx "vip-tag,3,0,1,2,0.0150,4" <<<"$(R automations)" && ok "automations: 3 runs, 1 dry, 2 actions, \$0.015 from ai_calls (no join double-count)" || bad "automations: $(R automations | tail -1)"
        grep -qx "update_shipping_address,web,2,1,0,50.0" <<<"$(R actions)" && ok "actions: confirm-card acceptance 50%" || bad "actions: $(R actions | tail -1)"
        grep -qx "web,1,50.00,525.7" <<<"$(R ai_revenue)" && ok "AI-attributed revenue \$50 → \$525.7 per AI dollar (typed decisions count as AI spend)" || bad "ai_revenue: $(R ai_revenue | tail -1)"
        [ "$(R guard | tail -2 | sort | tr '\n' ' ')" = "identity,2 off_topic,1 " ] && ok "guard stops counted by verdict" || bad "guard: $(R guard | tail -2 | tr '\n' ' ')"
        dec="$(R decisions)"
        grep -qx "guard,typesafe-ai:jev-1.13.0,2,0.000,0.000,200,290,0.000010" <<<"$dec" && grep -qx "guard,openai:mini,1,1.000,0.000,900,900,0.000100" <<<"$dec" \
          && grep -qx "triage,typesafe-ai:jev-1.13.0,1,0.000,1.000,50,50,0.000000" <<<"$dec" \
          && ok "decisions: per purpose × model — fallback 1/1, error 1/1, p50 200 / p95 290 ms, µ\$ exact" || bad "decisions: $(tr '\n' ' ' <<<"$dec")"
    else bad "schema generate/apply"; tail -5 "$T/dk.log" "$T/ddl.log" 2>/dev/null; fi
    dropdb --if-exists "$DB" >/dev/null 2>&1
else echo "  · local Postgres (or e2e deps) not available — SQL run skipped"; fi

echo "▶ ai-models (offline catalog fixture)"
H="$T/home"; mkdir -p "$H"
M() { env HOME="$H" XDG_CONFIG_HOME="$H/.config" AI_MODELS_URL="file://$KIT/tests/fixtures/models.json" "$KIT/bin/ai-models" "$@"; }
expect "search maps OpenRouter ids to app refs"       0 "acme:frontier-1"      M search acme
out="$(M suggest 2>&1)"; grep -q "other:no-tools-chat\|pix:image-gen" <<<"$out" && bad "suggest offered a tool-less / image model" || ok "suggest: tool-less + image-only models never offered for agent tasks"
dec="$(sed -n '/^▶ decide/,/^▶\|^$/p' <<<"$out")"; txt="$(sed '/^▶ decide/,$d' <<<"$out")"
grep -q "typesafe:jev-1.13" <<<"$dec" && ! grep -q "jev" <<<"$txt" && [ "$(grep -n 'jev' <<<"$dec" | head -1 | grep -c '~')" = 0 ] \
  && ok "suggest: decide lists decision models (pinned before ~latest), text tasks never get one" || bad "decide suggest: $dec"
expect "first 'new' saves a baseline"                  0 "baseline saved"       M new
python3 - "$KIT/tests/fixtures/models.json" "$T/models2.json" <<'PY'
import json, sys; d = json.load(open(sys.argv[1])); d["data"] = [m for m in d["data"] if m["id"] != "other/no-tools-chat"] + [{**d["data"][0], "id": "acme/frontier-2", "name": "Acme: Frontier 2"}]; json.dump(d, open(sys.argv[2], "w"))
PY
out="$(env HOME="$H" XDG_CONFIG_HOME="$H/.config" AI_MODELS_URL="file://$T/models2.json" "$KIT/bin/ai-models" new 2>&1)"
grep -q "acme:frontier-2" <<<"$out" && grep -q "other:no-tools-chat" <<<"$out" && ok "'new' reports added + retired models since last look" || bad "new diff: $out"
expect "providers lists every catalog provider + env" 0 "OPENROUTER_API_KEY"   M providers

echo "▶ ai-settings (isolated HOME + scratch repo — never touches real config)"
R2="$T/app"; mkdir -p "$R2"; git -C "$R2" init -q
S() { (cd "$R2" && env HOME="$H" XDG_CONFIG_HOME="$H/.config" PATH="/usr/bin:/bin:$(dirname "$(command -v node)")" "$KIT/bin/ai-settings" "$@"); }
out="$(printf 'sk-or-v1-SECRETVALUE123\n' | S key OPENROUTER_API_KEY 2>&1)"; code=$?
[ $code = 0 ] && ! grep -q SECRETVALUE <<<"$out" && ok "key read from stdin, never echoed" || bad "key ($code): $out"
[ "$(stat -f %Lp "$H/.config/ai-kit/secrets.env" 2>/dev/null || stat -c %a "$H/.config/ai-kit/secrets.env")" = 600 ] && grep -q "^OPENROUTER_API_KEY=" "$H/.config/ai-kit/secrets.env" && ok "secrets.env is 600 and holds the key" || bad "secrets file"
grep -q "^OPENROUTER_API_KEY=sk-or-v1-SECRETVALUE123" "$R2/.env" && grep -qxF ".env" "$R2/.gitignore" && ok "repo .env updated + gitignored" || bad "repo .env/.gitignore"
expect "key-mode mixed → AI_KEY_MODE in repo .env"   0 "mixed"                 S key-mode mixed
grep -qx "AI_KEY_MODE=mixed" "$R2/.env" && ok ".env has AI_KEY_MODE=mixed" || bad "key-mode not written"
expect "bad key-mode refused"                         1 "openrouter\|byok\|mixed" S key-mode everything
S secrets >/dev/null 2>&1; k1="$(grep '^AI_KEYS_SECRET=' "$R2/.env")"; a1="$(grep '^AI_APPROVAL_SECRET=' "$R2/.env")"
S secrets >/dev/null 2>&1; k2="$(grep '^AI_KEYS_SECRET=' "$R2/.env")"
[ -n "$k1" ] && [ -n "$a1" ] && [ "$k1" = "$k2" ] && [ "$(grep -c '^AI_KEYS_SECRET=' "$R2/.env")" = 1 ] && ok "secrets generated once; AI_KEYS_SECRET never rotated (stored keys stay decryptable)" || bad "secrets idempotency"
expect "fingerprint pro switch"                       0 "pro"                   S fingerprint pro
expect "evolve propose switch"                        0 "propose"               S evolve propose
expect "show reflects switches"                       0 "evolve +propose"       S show

echo "▶ ai-report db resolution (never prints credentials)"
printf 'DATABASE_URL=postgres://u:secretpw@db.railway.internal:5432/x\nDATABASE_PUBLIC_URL="postgres://u:secretpw@abc.proxy.rlwy.net:1234/railway"\n' > "$R2/.env.local"
out="$(cd "$R2" && env -u AI_DATABASE_URL -u DATABASE_URL -u DATABASE_PUBLIC_URL PATH="/usr/bin:/bin" "$KIT/bin/ai-report" --which-db 2>&1)"
grep -q "abc.proxy.rlwy.net" <<<"$out" && ok "skips *.railway.internal, picks DATABASE_PUBLIC_URL" || bad "which-db: $out"
grep -q secretpw <<<"$out" && bad "which-db leaked the password" || ok "output masks the password"
rm -f "$R2/.env.local"

echo "▶ ai-init (scratch app repo with Starter-Kit verify.sh + Marketing/Security Kit context)"
cat > "$R2/package.json" <<'J'
{"name":"demo","dependencies":{"ai":"^7.0.0","express":"^5.0.0","resend":"^6.0.0","telnyx":"^2.0.0","drizzle-orm":"^0.45.0"}}
J
mkdir -p "$R2/shared" "$R2/server/modules/visitors" "$R2/server/modules/assistant" "$R2/.agents"
echo 'export const users = pgTable("users", {}); export const orders = pgTable("orders", {}); export const deviceVisitors = pgTable("device_visitors", {});' > "$R2/shared/schema.ts"
echo 'export function publishVisitor() {}' > "$R2/server/modules/visitors/bus.ts"
echo 'app.use(compression()); res.setHeader("Content-Type", "text/event-stream");' > "$R2/server/index.ts"
printf '#!/usr/bin/env bash\nset -euo pipefail\nstep() { echo "── $1"; }\nstep "test"\ntrue\n\nprintf %s\\n' "'\\n✓ verify passed — every check green\\n'" > "$R2/verify.sh"; chmod +x "$R2/verify.sh"
echo "# Demo rules" > "$R2/CLAUDE.md"; echo "# Growth stack" > "$R2/.agents/growth-stack.md"; echo "# Security context" > "$R2/.agents/security-context.md"
I() { (cd "$R2" && env HOME="$H" XDG_CONFIG_HOME="$H/.config" AI_UPSTREAM="$T/upstream-none" PATH="$KIT/bin:/usr/bin:/bin:$(dirname "$(command -v node)")" bash "$KIT/install/init-project.sh"); }
mkdir -p "$T/upstream-none"
I >"$T/init.log" 2>&1 && ok "ai-init exits 0" || { bad "ai-init failed"; tail -20 "$T/init.log"; }
st="$R2/.agents/ai-stack.md"
grep -q "Email bot: resend" "$st" && grep -q "SMS bot: telnyx" "$st" && grep -q "device_visitors" "$st" && grep -q "server/modules/assistant" "$st" && grep -q "visitors/bus.ts" "$st" \
  && ok "ai-stack.md drafted from the repo (AI SDK, email/SMS providers, tables, existing assistant + live-visitors modules)" || { bad "ai-stack.md draft"; head -40 "$st"; }
grep -q "journey-analytics" "$st" && ok "detects Marketing Kit → tracking hand-off to journey-analytics" || bad "growth-stack detection"
for f in cases.json decisions.json promptfooconfig.yaml redteam.yaml; do [ -f "$R2/evals/$f" ] || bad "evals/$f not seeded"; done; ok "evals/ seeded (cases + decision suite + promptfoo eval + red team)"
grep -q "ai-kit:start" "$R2/CLAUDE.md" && [ ! -f "$R2/AGENTS.md" ] && ok "block in the real CLAUDE.md, no rival AGENTS.md" || bad "instructions block placement"
grep -q "custom-built assistant" "$R2/CLAUDE.md" && ok "identity rule reaches the repo's agent instructions" || bad "identity rule missing from block"
grep -q "ai-kit:growth:start" "$R2/.agents/growth-stack.md" && grep -q "ai-kit:surface:start" "$R2/.agents/security-context.md" && ok "hand-off blocks added to Marketing Kit growth-stack + Security Kit context" || bad "sibling hand-offs"
grep -qxF ".agents/ai-kit.env" "$R2/.gitignore" && ok ".gitignore protects ai-kit.env" || bad ".gitignore"
awk '/AI guard tests/{a=NR} /verify passed/{b=NR} END{exit !(a && b && a<b)}' "$R2/verify.sh" && ok "verify.sh step inserted before the final success line" || bad "verify.sh insertion"
for f in CLAUDE.md verify.sh .agents/growth-stack.md .agents/security-context.md .agents/ai-stack.md .gitignore; do cp "$R2/$f" "$T/$(echo "$f" | tr / _).1"; done
I >/dev/null 2>&1
same=1; for f in CLAUDE.md verify.sh .agents/growth-stack.md .agents/security-context.md .agents/ai-stack.md .gitignore; do cmp -s "$R2/$f" "$T/$(echo "$f" | tr / _).1" || { same=0; echo "      changed: $f"; }; done
[ $same = 1 ] && ok "re-run is idempotent (no duplicate blocks, stack kept)" || bad "re-run changed files"
(cd "$R2" && ./verify.sh >/dev/null 2>&1) && ok "verify.sh still GREEN (no ai:test script yet → step skipped)" || bad "verify.sh broke"
node -e 'const f=process.argv[1],p=require(f);p.scripts={"ai:test":"false"};require("fs").writeFileSync(f,JSON.stringify(p))' "$R2/package.json"
(cd "$R2" && ./verify.sh >/dev/null 2>&1); [ $? != 0 ] && ok "verify.sh goes RED when ai:test fails" || bad "verify.sh ignored a failing ai:test"
node -e 'const f=process.argv[1],p=require(f);p.scripts={"ai:test":"true"};require("fs").writeFileSync(f,JSON.stringify(p))' "$R2/package.json"

git -C "$R2" remote add origin https://github.com/test/app.git; I >/dev/null 2>&1
w="$R2/.github/workflows/ai-kit-sync.yml"
[ -f "$w" ] && grep -q "feelthefusion/ai-kit" "$w" && ! grep -q "__KIT_REPO__" "$w" && ok "GitHub app repo → webhook receiver workflow with the kit slug filled in" || bad "ai-kit-sync.yml"

R3="$T/late"; mkdir -p "$R3"; git -C "$R3" init -q; echo '{"name":"late"}' > "$R3/package.json"
(cd "$R3" && env HOME="$H" XDG_CONFIG_HOME="$H/.config" PATH="$KIT/bin:/usr/bin:/bin:$(dirname "$(command -v node)")" bash "$KIT/install/init-project.sh" >/dev/null 2>&1)
echo "# my edit: custom tracker" >> "$R3/.agents/ai-stack.md"; mkdir -p "$R3/.agents"; echo "# Growth stack" > "$R3/.agents/growth-stack.md"
(cd "$R3" && env HOME="$H" XDG_CONFIG_HOME="$H/.config" PATH="$KIT/bin:/usr/bin:/bin:$(dirname "$(command -v node)")" bash "$KIT/install/init-project.sh" >/dev/null 2>&1)
grep -q "Site-wide events: Marketing Kit journey-analytics" "$R3/.agents/ai-stack.md" && grep -q "my edit: custom tracker" "$R3/.agents/ai-stack.md" \
  && ok "Marketing Kit added later → drafted tracking line refreshed, user edits kept" || bad "late sibling refresh"

echo "▶ ai-doctor (app checks)"
D2() { (cd "$R2" && env HOME="$H" XDG_CONFIG_HOME="$H/.config" AI_UPSTREAM="$T/upstream-none" PATH="$KIT/bin:/usr/bin:/bin:$(dirname "$(command -v node)")" bash "$KIT/bin/ai-doctor" 2>&1); }
mkdir -p "$R2/.claude/worktrees/feat/server"; printf 'new ToolLoopAgent({ experimental_toolApprovalSecret });\napp.use(compression({ filter: (req, res) => !String(res.getHeader("Content-Type")).startsWith("text/event-stream") }));\n' > "$R2/.claude/worktrees/feat/server/agent.ts"
out="$(D2)"; code=$?
grep -q "site-agent present" <<<"$out" && bad "credited a worktree's agent to the checkout" || ok "code in .claude/worktrees (other branches) is never credited to this checkout"
rm -rf "$R2/.claude/worktrees"
grep -q "✗ compression() filter" <<<"$out" && [ $code != 0 ] && ok "flags the compression pitfall that freezes AI streams (exit $code)" || bad "compression pitfall not flagged ($code)"
grep -q "AI_APPROVAL_SECRET set" <<<"$out" && grep -q "key mode: mixed" <<<"$out" && ok "reads key mode + secrets from the repo env" || bad "env checks: $(grep -E 'key mode|APPROVAL' <<<"$out")"
echo 'app.use(compression({ filter: (req, res) => !String(res.getHeader("Content-Type") || "").startsWith("text/event-stream") && compression.filter(req, res) }));' > "$R2/server/index.ts"
grep -q "compression skips text/event-stream" <<<"$(D2)" && ok "passes once the filter checks the response Content-Type" || bad "fixed filter still flagged"
grep -q "typed decisions: off" <<<"$out" && ok "typed decisions reported off until a decide task exists" || bad "decide-off check: $(grep -i decision <<<"$out")"
mkdir -p "$R2/shared"; printf 'export const aiDefaults = { decide: { model: "typesafe-ai:jev-latest", fallbacks: ["openai:mini"] } };\n' > "$R2/shared/ai-config.ts"
out="$(D2)"; grep -q "decide → typesafe-ai:jev-latest" <<<"$out" && grep -q "floats — pin a Jev version" <<<"$out" && grep -q "decision suite: [0-9]* cases" <<<"$out" \
  && ok "decide task: floating jev-latest flagged, seeded decision suite counted" || bad "decide checks: $(grep -iE 'decide|decision|jev' <<<"$out" | tr '\n' ' ')"

echo "▶ an install never dirties its own clone (else self-update is blocked forever)"
CL="$T/clone"; git -C "$KIT" checkout-index -a --prefix="$CL/"   # the COMMITTED state, file modes included
( cd "$CL" && git init -q && git add -A && git -c user.name=t -c user.email=t@t commit -qm c )
( source "$CL/install/lib.sh" >/dev/null 2>&1; AI_BIN="$T/bin"; link_bins "$CL" >/dev/null 2>&1 )
[ -z "$(git -C "$CL" status --porcelain)" ] && ok "link_bins leaves the clone clean (scripts committed executable)" || bad "install dirtied the clone: $(git -C "$CL" status --porcelain | tr '\n' ' ')"
chmod -x "$CL/bin/ai-doctor"; ( source "$CL/install/lib.sh" >/dev/null 2>&1; KIT_NO_PULL=0 kit_self_update "$CL" 2>&1 ) | grep -q "local changes" && bad "a mode-only change still blocks self-update" || ok "a mode-only change never blocks self-update"

echo "▶ living updates: ai-update (event-driven, offline via local bare repos)"
LU="$T/lu"; mkdir -p "$LU/remotes" "$LU/home" "$LU/proj"
CLEANPATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin"   # no claude/hermes → nothing global is applied
cp -R "$KIT" "$LU/kit" && rm -rf "$LU/kit/.git" "$LU/kit/node_modules" "$LU/kit/tests/e2e/node_modules"
( cd "$LU/kit" && git init -q && git add -A && git -c user.name=t -c user.email=t@t commit -qm kit && git remote add origin https://github.com/test/kit )
repos="test/kit $(grep -v '^#' "$KIT/install/upstream-skills.tsv" | cut -f1 | cut -d/ -f1-2 | sort -u | tr '\n' ' ') $(grep -v '^#' "$KIT/install/claude-plugins.tsv" | cut -f2 | tr '\n' ' ')"
for r in $repos; do
    mkdir -p "$LU/remotes/$(dirname "$r")"; git init -q --bare "$LU/remotes/$r" 2>/dev/null
    c="$LU/c/$r"; git clone -q "$LU/remotes/$r" "$c" 2>/dev/null
    ( cd "$c" && git -c user.name=t -c user.email=t@t commit -q --allow-empty -m one && git push -q origin HEAD 2>/dev/null )
done
nrep="$(echo $repos | tr ' ' '\n' | sort -u | grep -c .)"
mu() { env -i HOME="$LU/home" PATH="$CLEANPATH" XDG_CONFIG_HOME="$LU/cfg" XDG_DATA_HOME="$LU/data" AI_GIT_BASE="file://$LU/remotes" AI_NO_PLUGINS=1 "$@"; }
mu "$LU/kit/bin/ai-update" >/dev/null 2>&1
n="$(python3 -c "import json;print(len(json.load(open('$LU/cfg/ai-kit/update-state.json'))['rev']))" 2>/dev/null)"
[ "$n" = "$nrep" ] && ok "first run records every component's revision ($n: kit + upstream repos + plugin marketplaces)" || bad "state records ($n, want $nrep)"
mu "$LU/kit/bin/ai-update" --check | grep -q "everything current" && ok "no upstream movement → nothing to do" || bad "idle check"
( cd "$LU/c/promptfoo/promptfoo" && git -c user.name=t -c user.email=t@t commit -q --allow-empty -m two && git push -q origin HEAD 2>/dev/null )
out="$(mu "$LU/kit/bin/ai-update" --check)"
grep -q "upstream:promptfoo/promptfoo" <<<"$out" && [ "$(grep -c '↑' <<<"$out")" = 1 ] && ok "upstream push detected — only the moved repo flagged" || bad "change detection: $out"
( cd "$LU/proj" && git init -q && mkdir -p .agents && echo "# stack" > .agents/ai-stack.md && echo stale > .agents/.ai-kit-version )
echo "done: x" > "$LU/cfg/ai-kit/update-notice.txt"
s=$(python3 -c 'import time;print(time.time())')
hout="$(echo "{\"cwd\":\"$LU/proj\",\"hook_event_name\":\"SessionStart\"}" | mu "$LU/kit/bin/ai-update" --hook)"
ms=$(python3 -c "import time;print(int((time.time()-$s)*1000))")
[ "$ms" -lt 2500 ] && ok "hook returns immediately (${ms} ms) — work happens in background" || bad "hook took ${ms} ms"
grep -q "^AI Kit auto-updated since your last session: done: x" <<<"$hout" && ok "Claude Code: previous run's updates → session context" || bad "claude notice: $hout"
for _ in $(seq 1 40); do [ "$(cat "$LU/proj/.agents/.ai-kit-version")" != stale ] && break; sleep 1; done
[ "$(cat "$LU/proj/.agents/.ai-kit-version")" = "$(git -C "$LU/kit" rev-parse --short=12 HEAD)" ] && ok "stale project re-synced to the kit in the background" || bad "project sync"
for _ in $(seq 1 10); do [ -d "$LU/cfg/ai-kit/update.lock" ] || break; sleep 1; done
hj="$(echo "{\"cwd\":\"$LU/proj\",\"hook_event_name\":\"on_session_start\"}" | mu "$LU/kit/bin/ai-update" --hook)"
python3 -c "import json,sys; d=json.loads(sys.argv[1]); assert 'AI Kit' in d['context']" "$hj" 2>/dev/null && ok "Hermes: notice delivered as {\"context\": …}" || bad "hermes notice: $hj"
echo '' | mu env AI_UPDATE=off "$LU/kit/bin/ai-update" --hook | grep -q . && bad "AI_UPDATE=off still ran" || ok "AI_UPDATE=off → hook is a no-op"
mkdir -p "$LU/cc"; echo '{"hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"mine.sh"}]}],"Stop":[{"hooks":[{"type":"command","command":"stop.sh"}]}]}}' > "$LU/cc/settings.json"
( source "$KIT/install/lib.sh" >/dev/null 2>&1; AI_BIN=/x; wire_claude_update_hook "$LU/cc"; wire_claude_update_hook "$LU/cc" ) >/dev/null
python3 - "$LU/cc/settings.json" <<'PY' && ok "SessionStart hook wired once; existing hooks kept" || bad "hook wiring"
import json, sys
h = json.load(open(sys.argv[1]))["hooks"]
cmds = [x["command"] for g in h["SessionStart"] for x in g["hooks"]]
assert cmds.count("/x/ai-update --hook") == 1 and "mine.sh" in cmds and h["Stop"], cmds
PY
python3 - "$KIT/.github/workflows/notify-projects.yml" "$KIT/templates/github/ai-kit-sync.yml" <<'PY' && ok "webhook workflows: dispatch-driven, no schedule, full-SHA pins" || bad "workflow shape"
import re, sys
a, b = (open(p).read() for p in sys.argv[1:3])
assert not re.search(r"^\s*(schedule|- cron):", a + b, re.M)
assert "repository_dispatch" in b and "types: [ai-kit-updated]" in b and "event_type=ai-kit-updated" in a
assert all(re.search(r"@[0-9a-f]{40}\b", l) for l in (a + b).splitlines() if "uses:" in l)
PY

echo "── $pass passed · $fail failed"
[ "$fail" = 0 ]
